export const LOGIN = 'login'
export const USER_INFO = 'userInfo'

export const ORDER_LIST = 'orderList'
export const ORDER_ITEM = 'orderItem'
export const ORDER_CREATE = 'orderCreate'
export const ORDER_UPDATE = 'orderUpdate'
export const ORDER_DELETE = 'orderDelete'

export const CLIENT_LIST = 'clientList'
export const CLIENT_ITEM = 'clientItem'
export const CLIENT_CREATE = 'clientCreate'
export const CLIENT_UPDATE = 'clientUpdate'
export const CLIENT_DELETE = 'clientDelete'

export const OUTSOURCE_LIST = 'timeSheetList'
export const OUTSOURCE_ITEM = 'timeSheetItem'
export const OUTSOURCE_CREATE = 'timeSheetCreate'
export const OUTSOURCE_UPDATE = 'timeSheetUpdate'
export const OUTSOURCE_DELETE = 'timeSheetDelete'

export const STAFF_LIST = 'staffList'
export const STAFF_ITEM = 'staffItem'
export const STAFF_CREATE = 'staffCreate'
export const STAFF_UPDATE = 'staffUpdate'
export const STAFF_DELETE = 'staffDelete'

export const TAGS_LIST = 'tagsList'
export const TAGS_ITEM = 'tagsItem'
export const TAGS_CREATE = 'tagsCreate'
export const TAGS_UPDATE = 'tagsUpdate'
export const TAGS_DELETE = 'tagsDelete'

export const CURRENCY_LIST = 'currencyList'
export const CURRENCY_ITEM = 'currencyItem'
export const CURRENCY_CREATE = 'currencyCreate'
export const CURRENCY_UPDATE = 'currencyUpdate'
export const CURRENCY_DELETE = 'currencyDelete'

export const BRANCH_LIST = 'branchList'
export const BRANCH_ITEM = 'branchItem'
export const BRANCH_CREATE = 'branchCreate'
export const BRANCH_UPDATE = 'branchUpdate'
export const BRANCH_DELETE = 'branchDelete'

export const GROUP_LIST = 'groupList'
export const GROUP_ITEM = 'groupItem'
export const GROUP_CREATE = 'groupCreate'
export const GROUP_UPDATE = 'groupUpdate'
export const GROUP_DELETE = 'groupDelete'

export const PERMISSION_LIST = 'permissionList'
export const PERMISSION_ITEM = 'permissionItem'
export const PERMISSION_CREATE = 'permissionCreate'
export const PERMISSION_UPDATE = 'permissionUpdate'
export const PERMISSION_DELETE = 'permissionDelete'

export const CONTRACT_LIST = 'contractList'
export const CONTRACT_ITEM = 'contractItem'
export const CONTRACT_CREATE = 'contractCreate'
export const CONTRACT_UPDATE = 'contractUpdate'
export const CONTRACT_DELETE = 'contractDelete'

export const ASSIGNMENT_LIST = 'assignmentList'
export const ASSIGNMENT_ITEM = 'assignmentItem'
export const ASSIGNMENT_CREATE = 'assignmentCreate'
export const ASSIGNMENT_UPDATE = 'assignmentUpdate'
export const ASSIGNMENT_DELETE = 'assignmentDelete'

export const POSITION_LIST = 'positionList'
export const POSITION_ITEM = 'positionItem'
export const POSITION_CREATE = 'positionCreate'
export const POSITION_UPDATE = 'positionUpdate'
export const POSITION_DELETE = 'positionDelete'

export const ROLE_LIST = 'roleList'
export const ROLE_ITEM = 'roleItem'
export const ROLE_CREATE = 'roleCreate'
export const ROLE_UPDATE = 'roleUpdate'
export const ROLE_DELETE = 'roleDelete'

export const BANK_ACCOUNT_LIST = 'bankAccountList'
export const BANK_ACCOUNT_ITEM = 'bankAccountItem'
export const BANK_ACCOUNT_CREATE = 'bankAccountCreate'
export const BANK_ACCOUNT_UPDATE = 'bankAccountUpdate'
export const BANK_ACCOUNT_DELETE = 'bankAccountDelete'

export const FEE_LIST = 'feeList'
export const FEE_ITEM = 'feeItem'
export const FEE_CREATE = 'feeCreate'
export const FEE_UPDATE = 'feeUpdate'
export const FEE_DELETE = 'feeDelete'

export const EXPENSE_LIST = 'expenseList'
export const EXPENSE_ITEM = 'expenseItem'
export const EXPENSE_CREATE = 'expenseCreate'
export const EXPENSE_UPDATE = 'expenseUpdate'
export const EXPENSE_DELETE = 'expenseDelete'

export const TIME_SHEET_LIST = 'timeSheetList'
export const TIME_SHEET_ITEM = 'timeSheetItem'
export const TIME_SHEET_CREATE = 'timeSheetCreate'
export const TIME_SHEET_UPDATE = 'timeSheetUpdate'
export const TIME_SHEET_DELETE = 'timeSheetDelete'

export const UNINVOICED_LIST = 'uninvoicedList'
export const UNINVOICED_ITEM = 'uninvoicedItem'
export const UNINVOICED_CREATE = 'uninvoicedCreate'
export const UNINVOICED_UPDATE = 'uninvoicedUpdate'
export const UNINVOICED_DELETE = 'uninvoicedDelete'

export const INVOICE_LIST = 'invoiceList'
export const INVOICE_ITEM = 'invoiceItem'
export const INVOICE_CREATE = 'invoiceCreate'
export const INVOICE_UPDATE = 'invoiceUpdate'
export const INVOICE_DELETE = 'invoiceDelete'
export const INVOICE_TOTAL_PAYMENT = 'invoiceTotalPayment'
export const INVOICE_MONTH_PAYMENT = 'invoiceMonthPayment'

