export const ORDER_LIST = 'orderList'
export const ORDER_ITEM = 'orderItem'
export const ORDER_CREATE = 'orderCreate'
export const ORDER_UPDATE = 'orderUpdate'
export const ORDER_DELETE = 'orderDelete'

export const STAFF_LIST = 'staffList'
export const STAFF_ITEM = 'staffItem'
export const STAFF_CREATE = 'staffCreate'
export const STAFF_UPDATE = 'staffUpdate'
export const STAFF_DELETE = 'staffDelete'

export const TAGS_LIST = 'tagsList'
export const TAGS_ITEM = 'tagsItem'
export const TAGS_CREATE = 'tagsCreate'
export const TAGS_UPDATE = 'tagsUpdate'
export const TAGS_DELETE = 'tagsDelete'

export const CURRENCY_LIST = 'currencyList'
export const CURRENCY_ITEM = 'currencyItem'
export const CURRENCY_CREATE = 'currencyCreate'
export const CURRENCY_UPDATE = 'currencyUpdate'
export const CURRENCY_DELETE = 'currencyDelete'

export const BRANCH_LIST = 'branchList'
export const BRANCH_ITEM = 'branchItem'
export const BRANCH_CREATE = 'branchCreate'
export const BRANCH_UPDATE = 'branchUpdate'
export const BRANCH_DELETE = 'branchDelete'

export const GROUP_LIST = 'groupList'
export const GROUP_ITEM = 'groupItem'
export const GROUP_CREATE = 'groupCreate'
export const GROUP_UPDATE = 'groupUpdate'
export const GROUP_DELETE = 'groupDelete'

export const PERMISSION_LIST = 'permissionList'
export const PERMISSION_ITEM = 'permissionItem'
export const PERMISSION_CREATE = 'permissionCreate'
export const PERMISSION_UPDATE = 'permissionUpdate'
export const PERMISSION_DELETE = 'permissionDelete'


export const CONTRACT_LIST = 'contractList'
export const CONTRACT_ITEM = 'contractItem'
export const CONTRACT_CREATE = 'contractCreate'
export const CONTRACT_UPDATE = 'contractUpdate'
export const CONTRACT_DELETE = 'contractDelete'

export const ASSIGMENT_LIST = 'assignmentList'
export const ASSIGMENT_ITEM = 'assignmentItem'
export const ASSIGMENT_CREATE = 'assignmentCreate'
export const ASSIGMENT_UPDATE = 'assignmentUpdate'
export const ASSIGMENT_DELETE = 'assignmentDelete'

export const POSITION_LIST = 'positionList'
export const POSITION_ITEM = 'positionItem'
export const POSITION_CREATE = 'positionCreate'
export const POSITION_UPDATE = 'positionUpdate'
export const POSITION_DELETE = 'positionDelete'
