export const ORDER_LIST = 'orderList'
export const ORDER_ITEM = 'orderItem'
export const ORDER_CREATE = 'orderCreate'
export const ORDER_UPDATE = 'orderUpdate'
export const ORDER_DELETE = 'orderDelete'

export const TAGS_LIST = 'orderList'
export const TAGS_ITEM = 'orderItem'
export const TAGS_CREATE = 'orderCreate'
export const TAGS_UPDATE = 'orderUpdate'
export const TAGS_DELETE = 'orderDelete'
